name: Show gh ref names (unit-test)
runs:
  using: "composite"
  steps:
    - name: Echo gh ref names (unit-test)
      run: |
        echo "github.sha="${{ github.sha }}
        echo "github.event_name="${{ github.event_name }}
        echo "github.ref="${{ github.ref }}
        echo "github.ref_name="${{ github.ref_name }}
        echo "github.base_ref="${{ github.base_ref }}
        echo "github.head_ref="${{ github.head_ref }}
