description: 'Sonar check'
inputs:
  GH_TOKEN:
    description: "Github token"
    required: true
  SNR_TOKEN:
    description: "Sonar token"
    required: true
name: Start Maven unit-tests
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ inputs.GT_TOKEN }}
        SONAR_TOKEN: ${{ inputs.SNR_TOKEN }}
      run: mvn -B clean verify sonar:sonar
        -Dsonar.qualitygate.wait=true
        -Dsonar.login=${{ inputs.SNR_TOKEN }}
        -Dsonar.projectKey=jashka34_jhp
        -Dsonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml
