description: 'Show Github context varibles'
name: Show Github context varibles
runs:
  using: "composite"
  steps:
    - name: Github context varibles
      shell: bash
      run: |
        echo "github.sha="${{ github.sha }}
        echo "github.event_name="${{ github.event_name }}
        echo "github.ref="${{ github.ref }}
        echo "github.ref_name="${{ github.ref_name }}
        echo "github.base_ref="${{ github.base_ref }}
        echo "github.head_ref="${{ github.head_ref }}
