name: Code Quality

on:
  
  push:
    branches: [ feature/** ]

jobs:

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Maven Verify
        run: mvn -B clean test
    

  linter:
    needs: [ unit-tests ]
    name: Linter (Checkstyle)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true
          JAVA_FILE_NAME: google-checkstyle.xml
          #VALIDATE_GOOGLE_JAVA_FORMAT: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  codecov:
    needs: [ unit-tests ]
    name: Codecov
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Maven Verify
        run: mvn -B clean test

      - name: Code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          #file: target/coverage/jacoco.xml
          fail_ci_if_error: true

      - name: ls
        run: |
          ls -lah target
