on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
