on:
  pull_request:
    branches:
      - '**'
jobs:
  show-gh-ref-names:
    name: Show gh ref names (pull-start)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show Github context
        uses: ./.github/actions/echo-github-context/
  check-pull-to-master:
    name: Check pull-request to master
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'master' && github.head_ref != 'release' }}
    steps:
      - name: Can't create pull-request to master, only release -> master available.
        uses: peter-evans/close-pull@v1
        with:
          pull-request-number: ${{ github.event.number }}
          comment: |
            :thumbsdown: :x: Auto-closing pull request.
            Because can't create pull-request to master, only release -> master available.
          delete-branch: false
  check-branch-format-1:
    name: Check branch format (feature|bugfix) (pull-request)
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'release' && (!startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'bugfix/')) }}
    steps:
      - name: Can't create pull-request from not (feature|bugfix) branch
        uses: peter-evans/close-pull@v1
        with:
          pull-request-number: ${{ github.event.number }}
          comment: |
            :thumbsdown: :x: Auto-closing pull request.
            Because you can't create pull-request from not (feature|bugfix) branch.
          delete-branch: false
