name: Push to all (except master, release, feature/**)
on:
  push:
    branches:
      - '**'
      - '!master'
      - '!release'
      - '!feature/**'
jobs:
#  show-gh-ref-names:
#    if: github.event.number == ''
#    name: Show gh ref names (pull start)
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Show Github context
#        uses: ./.github/actions/echo-github-context/
  check-branch-format-1:
    name: Check branch format (feature|bugfix)
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref == '' &&
           !(startsWith(github.ref_name, 'feature/') || startsWith(github.ref_name, 'bugfix/')) }}
    steps:
#      - name: Wrong branch name format (delete branch)
#        uses: dawidd6/action-delete-branch@v3.1.0
#        with:
#          github_token: ${{github.token}}
#          branches: ${{github.ref_name}}
      - name: Wrong branch name fromat  (exit 1)
        if: ${{ !(startsWith(github.ref_name, 'feature/') || startsWith(github.ref_name, 'bugfix/')) }}
        run: |
          echo "branch must be only (feature|bugfix)/**!"
          exit 1
