on:
  push:
    branches:
      - '**'
jobs:
  show-gh-ref-names:
    name: Show gh ref names
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show Github context
        uses: ./.github/actions/echo-github-context/
  check-branch-format-feature:
    name: Check branch format feature
    runs-on: ubuntu-latest
    steps:
      - name: Ref is feauture
        if: ${{ startsWith(github.ref_name, 'feature') }}
        run: echo "its feature!"
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Start tests
        uses: ./.github/actions/unit-tests/
          with:
            github.
