on:
  push:
    branches:
      - '**'
jobs:
  show-gh-ref-names:
    name: Show gh ref names
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show Github context
        uses: ./.github/actions/echo-github-context/
  check-branch-format-feature:
    name: Check branch format feature
    runs-on: ubuntu-latest
    if: github.ref_name != 'master' && github.ref_name != 'release'
    steps:
      - name: Ref is feature
        if: ${{ startsWith(github.ref_name, 'feature/') || startsWith(github.ref_name, 'bugfix/') }}
        run: echo "its feature!"
      - name: Ref is not feature (delete branch)
        if: ${{ !(startsWith(github.ref_name, 'feature/') || startsWith(github.ref_name, 'bugfix/')) }}
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: ${{github.ref_name}}
      - name: Ref is not feature (exit 1)
        run: |
          echo "branch must be only (feature|bugfix)/**!"
          exit 1
