name: Release Draft

on:
  push:
    branches:
      - master

jobs:
  if: 1 == 2
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
